services:

  app:
    image: roti4wmde/wikidata-dump-processing
    volumes:
      - app-cache:/root/.cache
      # - type: bind
      #   source: .
      #   target: /workspace
      - type: bind
        source: ${WIKIDATA_DUMP_FILE}
        target: /mnt/wddump.json.gz    
      - type: bind
        source: ${LABELS_DB_FILE}
        target: /mnt/entities.db

    # entrypoint: ["bash"]
    # entrypoint: ["/entrypoint-worker.sh"]
    # command: ["dask", "scheduler"]
    # command: ["python", "/workspace/wddump_build_label_db.py"]

    # ports:
    #   - 8787:8787

    # GPU access for ROCm (AMD)
    # devices:
    #   - /dev/dri:/dev/dri
    #   - /dev/kfd:/dev/kfd

    network_mode: host

volumes:
  app-cache:
